[build]
  publish = "public"
  command = "hugo"

[context.production.environment]
  HUGO_VERSION = "0.140.2" # Replace with the latest stable version
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
