[build]
  publish = "public"
  command = "npm run install-deps --prefix themes/hugo-tailwind-theme && npm run build --prefix themes/hugo-tailwind-theme && hugo"

[context.production.environment]
  HUGO_VERSION = "0.140.2" # Replace with the latest stable version
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
